
FROM python:3.10-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
ENV MODEL_PATH=artifacts/model.joblib
CMD ["uvicorn", "src.serve_fastapi:app", "--host", "0.0.0.0", "--port", "8000"]
